12 create runner class
Deltares-research/pywanda-hydra pull request #22
Opened 2024-10-23 08:20 UTC by LuisFelipe-PE

This pull request introduces the runner_object and the test file for the runner object. Is also includes the modifications for the config files to run in win32.

2024-10-23 09:03 UTC, vanmeerkerk requested changes
See comments

2024-10-23 09:03 UTC, vanmeerkerk commented on .github/workflows/ci.yml
> +    runs-on: windows-latest
Why do you need to change the ci files? These are run by the continuous integration environment in github and I believe that runs on ubuntu not windows?

2024-10-23 09:03 UTC, vanmeerkerk commented on src/pywandahydra/entities/runner_object.py
> +        print("Save model input")
Why would you save the model input when you performed no changes to the model?

2024-10-23 09:03 UTC, vanmeerkerk commented on src/pywandahydra/entities/runner_object.py
> +        result: list of strings
The Returns are not correct; the method currently returns None.

2024-10-23 09:03 UTC, vanmeerkerk commented on src/pywandahydra/entities/runner_object.py
> +            print(e)
These errors need to be written to a log. Is there a logging module in the package?

@samvanderzwan

2024-10-23 09:03 UTC, vanmeerkerk commented on unit_test/entities/test_runner_object.py
> +class MyTest(unittest.TestCase):
The test should have a clear name and follow the convention ClassNameTest in this case RunnerObjectTest

2024-10-23 09:03 UTC, vanmeerkerk commented on unit_test/entities/test_runner_object.py
> +    def test_runner_object(self) -> None:
The test should follow the Arrange-Act-Assert structure for example see the below code:

``
     def test_set_physical_properties_missing_key(self) -> None:
          """Test the set_physical_properties method."""
          # arrange
          physical_properties_dict = {
              PROPERTY_DIAMETER: 0.5,
              PROPERTY_LENGTH: 2000.0,
          }
  
          # act
          with self.assertRaises(ValueError) as cm:
              self.asset.set_physical_properties(physical_properties=physical_properties_dict)  # act
  
          # assert
          self.assertIsInstance(cm.exception, ValueError)
          self.assertEqual(
              str(cm.exception), f"Property {PROPERTY_ROUGHNESS} is missing in physical_properties"
          )
``

2024-10-23 09:03 UTC, vanmeerkerk commented on unit_test/simulation/Sewage_transient_WPS.rtf
The RTF file is not necessary and I believe you can put them on the gitignore list

2024-10-23 09:03 UTC, vanmeerkerk commented on unit_test/simulation/Sewage_transient_WPS.wdd
Maybe this can also be put in the gitignore list? Only keep the .csv, .wdi .wdx .wdo .wps

2024-10-23 09:03 UTC, vanmeerkerk commented on unit_test/test_main.py
> +    def setUp(self) -> None:
Why did you make this test?

2024-10-24 12:54 UTC, LuisFelipe-PE commented on src/pywandahydra/entities/runner_object.py
> +        print("Save model input")
Fixed, the save input will be included in the parameter file itself

2024-10-24 12:55 UTC, LuisFelipe-PE commented on src/pywandahydra/entities/runner_object.py
> +        result: list of strings
Changed the result  to none

2024-10-28 13:17 UTC, vanmeerkerk commented on .github/workflows/ci.yml
> +    runs-on: windows-latest
Checked with @samvanderzwan; windows is required for pywanda as it can not run on a linux machine.

2026-03-16 09:53 UTC, closed without merging